name: CI-android

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      # The following input and its usage are based on the "rclone/rclone" project.
      # https://github.com/rclone/rclone/blob/c1f5df209024c79028c98134b703b31d599befac/.github/workflows/build.yml#L24
      # Copyright (C) 2012 by Nick Craig-Wood http://www.craig-wood.com/nick/. Licensed under MIT.
      manual:
        description: Manual run (bypass default conditions)
        required: true
        type: choice
        default: 'TRUE'
        options:
          - 'TRUE'

jobs:
  test:
    if: >-
      inputs.manual || (
        github.repository == 'jurplel/install-qt-action' && (
          github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name ||
          github.event.pull_request.user.login == 'dependabot[bot]'
        )
      )
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - windows-2025
          - macos-26
          - macos-26-intel
        qt:
          - version: "5.15.2"
            requested: "5.15.2"
            ndk-version: r21e
            modules:
            example-archives: qtbase qtsensors
            example-modules:
            example-project: accelbubble
          - version: "6.3.2"
            requested: "6.3.2"
            ndk-version: r21e
            modules: qtsensors
            example-archives: qtbase
            example-modules:  qtsensors
            example-project: accelbubble
          # https://doc.qt.io/archives/qt-6.7/supported-platforms.html
          # https://wiki.qt.io/Qt_6.7_Release
          - version: "6.7.3"
            requested: ">=6.7.*,<6.8.0"
            ndk-version: r26b
            modules: qtsensors
            example-archives: qtbase
            example-modules:  qtsensors
            example-project: sensorsshowcase  # since Qt 6.5
          # https://doc.qt.io/qt-6.10/supported-platforms.html
          # https://wiki.qt.io/Qt_6.10_Release
          - version: "6.10.3"
            requested: "<6.11.0"
            ndk-version: r27c
            modules: qtsensors
            example-archives: qtbase
            example-modules:  qtsensors
            example-project: sensorsshowcase  # since Qt 6.5
          # Installing Qt 6.11 on Windows is broken till aqtinstall v3.3.0 (the latest version so far)
          # - version: "6.11.2"
          #   ...

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: action/

      - run: |
          cd action
          npm ci || npm install
        shell: bash

      - run: |
          cd action
          npm run build

      # See the root "action.yml" file.
      - name: Use local built internal action (hack)
        run: |
          sed -i.bak 's|uses: $/action|uses: ./action|' action.yml
          diff -u action.yml.bak action.yml || true
          git status --porcelain
        shell: bash

      - name: Install Qt
        uses: ./
        with:
          target: android
          modules: ${{ matrix.qt.modules }}
          version: ${{ matrix.qt.requested }}
          examples: true
          example-archives: ${{ matrix.qt.example-archives }}
          example-modules:  ${{ matrix.qt.example-modules }}

      - name: Test QT_HOST_PATH
        if: ${{ startsWith(matrix.qt.version, '6.') }}
        shell: pwsh
        run: |
          $qmakeHostPrefix = [string](Resolve-Path -Path (qmake -query QT_HOST_PREFIX))
          if ($env:QT_HOST_PATH -ne $qmakeHostPrefix) {
            throw "QT_HOST_PATH should match qmake's QT_HOST_PREFIX."
          }
          if ($env:QT_HOST_PATH -eq $env:QT_ROOT_DIR) {
            throw "QT_HOST_PATH and QT_ROOT_DIR should be different."
          }
          if ((Split-Path -Path $env:QT_HOST_PATH -Parent) -ne (Split-Path -Path $env:QT_ROOT_DIR -Parent)) {
            throw "QT_HOST_PATH and QT_ROOT_DIR should have the same parent directory."
          }
          Write-Host "All tests passed!"

      - name: Install Android NDK
        shell: bash
        # Links to NDK are at https://github.com/android/ndk/wiki/Unsupported-Downloads
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            TARGET_ARCH="linux"
          elif [[ "${RUNNER_OS}" == "Windows" ]]; then
            TARGET_ARCH="windows"
          else
            TARGET_ARCH="darwin"
          fi
          NDK_VER_NUM=$(echo ${{ matrix.qt.ndk-version }} | sed -E -e 's/r([0-9]+).*/\1/g')
          # If it's older than 23, append -x86_64
          if (( "${NDK_VER_NUM}" < 23 )); then
            TARGET_ARCH="${TARGET_ARCH}-x86_64"
          fi;
          curl -O "https://dl.google.com/android/repository/android-ndk-${{ matrix.qt.ndk-version }}-${TARGET_ARCH}.zip"
          unzip "android-ndk-${{ matrix.qt.ndk-version }}-${TARGET_ARCH}.zip"

      - name: Build test project
        env:
          QT_VERSION: ${{ matrix.qt.version }}
          EXAMPLE_PROJECT: ${{ matrix.qt.example-project }}
        run: |
          export ANDROID_NDK_ROOT=$(pwd)/android-ndk-${{ matrix.qt.ndk-version }}
          cd ../Qt/Examples/Qt-${QT_VERSION}/sensors/${EXAMPLE_PROJECT}
          qmake || qmake.bat
          make
        shell: bash
